steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project123-281514/github.com/keerthukumar/helloworld_gcp:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project123-281514/github.com/keerthukumar/helloworld_gcp:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'hello-world-project', '--region=us-central1', '--platform=managed', '--image=gcr.io/project123-281514/github.com/keerthukumar/helloworld_gcp:$COMMIT_SHA']
